terminal: wezterm

root:
  name: envs
  children:
    - name: local
      children:
        - name: godoc
          children:
            - onExpand: >
                go list std
              children:
                - onExpand: go doc -short $current | grep '^[ ]*func' | sed -E 's/^[ ]*func ([^[(]+).*/\1/'
                  children:
                  - onSelect: go doc $parent.$current | less
